"""
Tests for handover/mcp_server.py — Phase 6 MCP server + v1.1.1 four tools.

The MCP SDK is mocked so these tests run without `pip install handover[mcp]`.
Tests verify:
  - run_handover tool logic (pipeline integration + .handover/ mention)
  - handover_status, handover_reverse, handover_list impls (v1.1.1)
  - Missing dependency error handling
  - CLI `handover mcp` subcommand handles missing mcp package
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

from click.testing import CliRunner

from handover.cli import main
from handover.models import SessionContext, SessionMeta

FIXTURES = Path(__file__).parent / "fixtures"


# ---------------------------------------------------------------------------
# Helpers to mock the mcp package
# ---------------------------------------------------------------------------


def _inject_mcp_mock() -> dict[str, MagicMock]:
    """Inject minimal mcp stubs into sys.modules so mcp_server can be imported."""
    mcp_mock = MagicMock()
    fastmcp_mock = MagicMock()
    server_mock = MagicMock()
    mocks = {
        "mcp": mcp_mock,
        "mcp.server": server_mock,
        "mcp.server.fastmcp": fastmcp_mock,
    }
    for name, mock in mocks.items():
        sys.modules.setdefault(name, mock)
    return mocks


def _remove_mcp_mock(originals: dict[str, MagicMock]) -> None:
    for name in originals:
        sys.modules.pop(name, None)
    # Also evict mcp_server from cache so it re-imports cleanly
    sys.modules.pop("handover.mcp_server", None)


# ---------------------------------------------------------------------------
# run_handover tool function (unit tests)
# ---------------------------------------------------------------------------


class TestRunHandoverTool:
    """Test the run_handover_impl() function in isolation (no MCP SDK needed)."""

    def _invoke(
        self,
        input_file: str,
        output_dir: str,
        source: str = "auto",
        target: str = "claude-code",
        no_llm: bool = True,
    ) -> str:
        """Call run_handover_impl directly — no MCP stubs needed."""
        from handover.mcp_server import run_handover_impl

        return run_handover_impl(
            input_file=input_file,
            output_dir=output_dir,
            source=source,
            target=target,
            no_llm=no_llm,
        )

    def test_tool_returns_string(self, tmp_path: Path) -> None:
        result = self._invoke(
            input_file=str(FIXTURES / "claude_single.json"),
            output_dir=str(tmp_path),
            no_llm=True,
        )
        assert isinstance(result, str)

    def test_tool_writes_files(self, tmp_path: Path) -> None:
        self._invoke(
            input_file=str(FIXTURES / "claude_single.json"),
            output_dir=str(tmp_path),
            no_llm=True,
        )
        assert (tmp_path / "CLAUDE.md").exists()
        assert (tmp_path / "PLAN.md").exists()

    def test_tool_returns_goal_info(self, tmp_path: Path) -> None:
        result = self._invoke(
            input_file=str(FIXTURES / "claude_single.json"),
            output_dir=str(tmp_path),
            no_llm=True,
        )
        assert "Goal:" in result

    def test_tool_missing_input_returns_error(self, tmp_path: Path) -> None:
        result = self._invoke(
            input_file="/nonexistent/file.json",
            output_dir=str(tmp_path),
        )
        assert "Error" in result

    def test_tool_target_codex(self, tmp_path: Path) -> None:
        self._invoke(
            input_file=str(FIXTURES / "claude_single.json"),
            output_dir=str(tmp_path),
            target="codex",
            no_llm=True,
        )
        assert (tmp_path / "AGENTS.md").exists()

    def test_tool_target_all(self, tmp_path: Path) -> None:
        self._invoke(
            input_file=str(FIXTURES / "claude_single.json"),
            output_dir=str(tmp_path),
            target="all",
            no_llm=True,
        )
        assert (tmp_path / "CLAUDE.md").exists()
        assert (tmp_path / "AGENTS.md").exists()

    def test_tool_mentions_handover_dir(self, tmp_path: Path) -> None:
        """v1.1.1: run_handover return string mentions .handover/ when it exists."""
        result = self._invoke(
            input_file=str(FIXTURES / "claude_single.json"),
            output_dir=str(tmp_path),
            no_llm=True,
        )
        # .handover/ is generated by the v1.1.0 universal generator
        if (tmp_path / ".handover").is_dir():
            assert ".handover/:" in result


# ---------------------------------------------------------------------------
# v1.1.1 Tool: handover_status
# ---------------------------------------------------------------------------


class TestHandoverStatusTool:
    """Unit tests for handover_status_impl (reads .handover/work/backlog.json)."""

    @staticmethod
    def _write_backlog(project: Path, tasks: list[dict]) -> Path:
        backlog_dir = project / ".handover" / "work"
        backlog_dir.mkdir(parents=True, exist_ok=True)
        data = {
            "schema_version": "1.0",
            "updated_at": "2026-04-09T10:00:00Z",
            "project": "test-project",
            "tasks": tasks,
            "milestones": [],
        }
        path = backlog_dir / "backlog.json"
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        return path

    def test_reads_backlog_json(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_status_impl

        self._write_backlog(
            tmp_path,
            [
                {
                    "id": "task-001",
                    "title": "Scaffold FastAPI",
                    "priority": "high",
                    "done": True,
                    "done_at": "2026-04-08T12:00:00Z",
                },
                {
                    "id": "task-002",
                    "title": "Add JWT middleware",
                    "priority": "high",
                    "done": False,
                },
                {"id": "task-003", "title": "Define schema", "priority": "medium", "done": False},
            ],
        )
        result = handover_status_impl(project_dir=str(tmp_path))

        assert "Project: test-project" in result
        assert "Progress: 1/3 tasks complete" in result
        assert "High priority remaining:" in result
        assert "Add JWT middleware" in result
        assert "Next task: Add JWT middleware" in result
        assert "Last completed: Scaffold FastAPI" in result
        assert "2026-04-08" in result

    def test_missing_file_returns_message(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_status_impl

        result = handover_status_impl(project_dir=str(tmp_path))
        assert "No backlog.json found" in result
        assert "Run handover first" in result

    def test_all_done_hides_next_task(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_status_impl

        self._write_backlog(
            tmp_path,
            [
                {
                    "id": "t1",
                    "title": "A",
                    "priority": "high",
                    "done": True,
                    "done_at": "2026-04-01T10:00:00Z",
                },
                {
                    "id": "t2",
                    "title": "B",
                    "priority": "medium",
                    "done": True,
                    "done_at": "2026-04-02T10:00:00Z",
                },
            ],
        )
        result = handover_status_impl(project_dir=str(tmp_path))
        assert "Progress: 2/2 tasks complete" in result
        assert "Next task:" not in result
        assert "Last completed: B" in result

    def test_none_done_shows_next_only(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_status_impl

        self._write_backlog(
            tmp_path,
            [
                {"id": "t1", "title": "First thing", "priority": "medium", "done": False},
                {"id": "t2", "title": "Second thing", "priority": "low", "done": False},
            ],
        )
        result = handover_status_impl(project_dir=str(tmp_path))
        assert "Progress: 0/2 tasks complete" in result
        assert "Next task: First thing" in result
        assert "Last completed:" not in result
        # No high-priority items → no "High priority" block
        assert "High priority remaining:" not in result

    def test_malformed_backlog_json_returns_error(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_status_impl

        backlog_dir = tmp_path / ".handover" / "work"
        backlog_dir.mkdir(parents=True)
        (backlog_dir / "backlog.json").write_text("{not-json", encoding="utf-8")

        result = handover_status_impl(project_dir=str(tmp_path))
        assert "Error reading" in result


# ---------------------------------------------------------------------------
# v1.1.1 Tool: handover_reverse
# ---------------------------------------------------------------------------


class TestHandoverReverseTool:
    """Unit tests for handover_reverse_impl (mocks reverse + discover_sessions)."""

    def _fake_session(self, tmp_path: Path) -> SessionMeta:
        file = tmp_path / "fake-session.jsonl"
        file.write_text("", encoding="utf-8")
        return SessionMeta(
            session_id="abcdef1234567890",
            project_path=str(tmp_path),
            file_path=file,
            started_at="2026-04-08T09:00:00Z",
            git_branch="main",
            message_count=5,
            size_bytes=1024,
        )

    def test_calls_pipeline(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_reverse_impl

        fake_session = self._fake_session(tmp_path)
        fake_context = SessionContext(
            session_id="abcdef1234567890",
            git_branch="main",
            files_changed=[],  # len = 0, just for counting
            commands_run=["pytest", "ruff"],
            decisions=["Chose pytest over unittest", "Used FastAPI over Flask"],
            next_steps=["Write docs", "Add integration tests"],
        )

        with (
            patch(
                "handover.parsers.claude_code.ClaudeCodeSessionParser.discover_sessions",
                return_value=[fake_session],
            ),
            patch("handover.reverse.reverse", return_value=fake_context),
            patch(
                "handover.generator.Generator.generate_handover", return_value={"HANDOVER.md": ""}
            ),
        ):
            result = handover_reverse_impl(
                project_dir=str(tmp_path),
                output_dir=str(tmp_path),
                no_llm=True,
            )

        assert "Session: abcdef12" in result
        assert "Branch: main" in result
        assert "Files changed: 0" in result
        assert "Commands run: 2" in result
        assert "Key decisions made:" in result
        assert "Chose pytest over unittest" in result
        assert "Recommended next steps:" in result
        assert "Full summary written to:" in result
        assert "HANDOVER.md" in result

    def test_no_sessions_returns_message(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_reverse_impl

        with patch(
            "handover.parsers.claude_code.ClaudeCodeSessionParser.discover_sessions",
            return_value=[],
        ):
            result = handover_reverse_impl(project_dir=str(tmp_path))
        assert "No Claude Code sessions found" in result
        assert "Run a Claude Code session first" in result

    def test_reverse_exception_surfaces_error(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_reverse_impl

        fake_session = self._fake_session(tmp_path)
        with (
            patch(
                "handover.parsers.claude_code.ClaudeCodeSessionParser.discover_sessions",
                return_value=[fake_session],
            ),
            patch("handover.reverse.reverse", side_effect=ValueError("boom")),
        ):
            result = handover_reverse_impl(project_dir=str(tmp_path))
        assert "Error reading session" in result
        assert "boom" in result

    def test_default_output_is_project_dir(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_reverse_impl

        fake_session = self._fake_session(tmp_path)
        fake_context = SessionContext(session_id="deadbeef" * 2, git_branch="main")

        captured: dict[str, Path] = {}

        def _fake_gen(self, context, output_dir, dry_run=False):  # noqa: ARG001
            captured["output_dir"] = output_dir
            return {"HANDOVER.md": ""}

        with (
            patch(
                "handover.parsers.claude_code.ClaudeCodeSessionParser.discover_sessions",
                return_value=[fake_session],
            ),
            patch("handover.reverse.reverse", return_value=fake_context),
            patch("handover.generator.Generator.generate_handover", new=_fake_gen),
        ):
            handover_reverse_impl(project_dir=str(tmp_path))  # no output_dir

        assert captured["output_dir"] == tmp_path.resolve()


# ---------------------------------------------------------------------------
# v1.1.1 Tool: handover_list
# ---------------------------------------------------------------------------


class TestHandoverListTool:
    """Unit tests for handover_list_impl (lists conversations in an export)."""

    def test_returns_conversations_from_bulk(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_list_impl

        result = handover_list_impl(input_file=str(FIXTURES / "claude_bulk.jsonl"))
        assert "Found" in result
        assert "conversation" in result
        assert "claude_bulk.jsonl" in result
        # At least one conversation title from the fixture
        assert "Use run_handover" in result

    def test_missing_file_returns_message(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_list_impl

        result = handover_list_impl(input_file="/nonexistent/file.json")
        assert "File not found" in result

    def test_empty_conversations(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_list_impl

        fake = tmp_path / "fake.json"
        fake.write_text("[]", encoding="utf-8")

        # Force parser to return [] regardless of format detection
        with (
            patch("handover.mcp_server.detect_source", return_value="claude")
            if False
            else patch("handover.parsers.claude.ClaudeParser.list_conversations", return_value=[]),
            patch("handover.parsers.detect_source", return_value="claude"),
        ):
            result = handover_list_impl(input_file=str(fake))
        assert "No conversations found" in result

    def test_caps_at_twenty(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_list_impl

        fake = tmp_path / "fake.json"
        fake.write_text("[]", encoding="utf-8")

        many = [{"id": f"id{i:03d}", "date": "2026-04-01", "title": f"Conv {i}"} for i in range(25)]
        with (
            patch("handover.parsers.claude.ClaudeParser.list_conversations", return_value=many),
            patch("handover.parsers.detect_source", return_value="claude"),
        ):
            result = handover_list_impl(input_file=str(fake))

        assert "Found 25 conversation(s)" in result
        assert "... and 5 more" in result
        # Only the first 20 titles appear; "Conv 20" (the 21st) must not
        assert "Conv 19" in result
        assert "Conv 20" not in result

    def test_parser_exception_surfaces_error(self, tmp_path: Path) -> None:
        from handover.mcp_server import handover_list_impl

        fake = tmp_path / "fake.json"
        fake.write_text("[]", encoding="utf-8")

        with (
            patch(
                "handover.parsers.claude.ClaudeParser.list_conversations",
                side_effect=ValueError("bad format"),
            ),
            patch("handover.parsers.detect_source", return_value="claude"),
        ):
            result = handover_list_impl(input_file=str(fake))
        assert "Error reading" in result
        assert "bad format" in result


# ---------------------------------------------------------------------------
# CLI handover mcp subcommand
# ---------------------------------------------------------------------------


class TestMCPCLI:
    def test_mcp_missing_dependency_shows_install_hint(self) -> None:
        runner = CliRunner()
        # Simulate ImportError when importing mcp_server
        with patch("handover.cli.run_mcp_server.callback") as _:
            pass  # just check the command exists

        # Test the import error path by temporarily hiding mcp
        orig = sys.modules.get("handover.mcp_server")
        sys.modules["handover.mcp_server"] = None  # type: ignore[assignment]
        try:
            result = runner.invoke(main, ["mcp"])
            # Should show an install hint, not a traceback
            assert result.exit_code != 0 or "mcp" in result.output.lower()
        finally:
            if orig is not None:
                sys.modules["handover.mcp_server"] = orig
            else:
                sys.modules.pop("handover.mcp_server", None)

    def test_mcp_command_registered(self) -> None:
        """Verify that `handover mcp` is a registered subcommand."""
        runner = CliRunner()
        result = runner.invoke(main, ["--help"])
        assert "mcp" in result.output
