"""
handover/targets/aider.py

Target adapter for aider: generates .aider.conf.yml.

Format (stdlib string rendering — no PyYAML required):
  model: gpt-4o
  auto-commits: false
  conventions:
    - "<decision>"

Phase 5 — Multi-Target Agents.
"""

from __future__ import annotations

from pathlib import Path

from handover.models import HandoverContext
from handover.targets.base import BaseTarget

_OUTPUT_FILENAME = ".aider.conf.yml"


class AiderTarget(BaseTarget):
    """Generates .aider.conf.yml for aider."""

    @property
    def name(self) -> str:
        """Target identifier: 'aider'."""
        return "aider"

    def generate(
        self,
        context: HandoverContext,
        output_dir: Path,
        dry_run: bool = False,
    ) -> list[Path]:
        """
        Generate .aider.conf.yml from the HandoverContext.

        Args:
            context: Populated HandoverContext.
            output_dir: Directory to write the output file.
            dry_run: If True, return expected path without writing.

        Returns:
            [output_dir/.aider.conf.yml]
        """
        output_path = output_dir / _OUTPUT_FILENAME
        if not dry_run:
            output_dir.mkdir(parents=True, exist_ok=True)
            output_path.write_text(self._render(context), encoding="utf-8")
        return [output_path]

    def _render(self, context: HandoverContext) -> str:
        """Render the .aider.conf.yml content from context."""
        lines: list[str] = [
            "# Generated by handover — https://github.com/mohankrishnaalavala/handover",
            "model: gpt-4o",
            "auto-commits: false",
        ]

        conventions = [d.decision.strip() for d in context.decisions if d.decision.strip()]
        if conventions:
            lines.append("conventions:")
            for convention in conventions:
                # Escape double quotes inside the value
                safe = convention.replace('"', '\\"')
                lines.append(f'  - "{safe}"')

        if context.goal:
            lines.append("")
            lines.append(f"# Goal: {context.goal}")

        return "\n".join(lines) + "\n"
