"""
handover/targets/copilot.py

Target adapter for GitHub Copilot: generates .github/copilot-instructions.md.

The file `.github/copilot-instructions.md` is the official GitHub Copilot
workspace context file, documented at:
  https://docs.github.com/en/copilot/customizing-copilot/adding-repository-instructions

It provides Copilot with project-specific context: goals, tech stack, coding
conventions, constraints, and the task list for the current session.

Phase 6 — Agent-Aware Output.
"""

from __future__ import annotations

from pathlib import Path

from handover.models import HandoverContext
from handover.targets.base import BaseTarget

_GITHUB_DIR = ".github"
_OUTPUT_FILENAME = "copilot-instructions.md"


class CopilotTarget(BaseTarget):
    """Generates .github/copilot-instructions.md for GitHub Copilot."""

    @property
    def name(self) -> str:
        """Target identifier: 'copilot'."""
        return "copilot"

    def describe(self) -> dict[str, str]:
        """Return human-readable metadata about this target."""
        return {
            "name": "copilot",
            "description": (
                "GitHub Copilot — generates .github/copilot-instructions.md "
                "(official Copilot workspace context file)"
            ),
        }

    def generate(
        self,
        context: HandoverContext,
        output_dir: Path,
        dry_run: bool = False,
    ) -> list[Path]:
        """
        Generate .github/copilot-instructions.md from the HandoverContext.

        Args:
            context: Populated HandoverContext.
            output_dir: Root directory for output (the .github/ subdir is created inside).
            dry_run: If True, return expected path without writing.

        Returns:
            [output_dir/.github/copilot-instructions.md]
        """
        github_dir = output_dir / _GITHUB_DIR
        output_path = github_dir / _OUTPUT_FILENAME
        if not dry_run:
            github_dir.mkdir(parents=True, exist_ok=True)
            output_path.write_text(self._render(context), encoding="utf-8")
        return [output_path]

    def _render(self, context: HandoverContext) -> str:
        """Render copilot-instructions.md content from context."""
        lines: list[str] = [
            "# Copilot Instructions",
            "",
            "> This file provides GitHub Copilot with project context for the current session.",
            "> It was generated by [handover](https://github.com/mohankrishnaalavala/handover).",
            "",
        ]

        lines += ["## Goal", "", context.goal or "(none)", ""]

        if context.tech_stack:
            lines.append("## Tech Stack")
            lines.append("")
            for key, value in context.tech_stack.items():
                lines.append(f"- **{key}**: {value}")
            lines.append("")

        if context.decisions:
            lines.append("## Key Decisions")
            lines.append("")
            for decision in context.decisions:
                entry = f"- **{decision.topic}**: {decision.decision}"
                if decision.rationale:
                    entry += f"\n  _Rationale: {decision.rationale}_"
                lines.append(entry)
            lines.append("")

        if context.constraints:
            lines.append("## Constraints")
            lines.append("")
            for constraint in context.constraints:
                lines.append(f"- {constraint}")
            lines.append("")

        if context.non_goals:
            lines.append("## Non-Goals")
            lines.append("")
            for non_goal in context.non_goals:
                lines.append(f"- {non_goal}")
            lines.append("")

        if context.tasks:
            lines.append("## Current Tasks")
            lines.append("")
            for i, task in enumerate(context.tasks, 1):
                status = "[x]" if task.done else "[ ]"
                priority = " _(high priority)_" if task.priority == "high" else ""
                lines.append(f"{i}. {status} {task.title}{priority}")
                if task.description:
                    lines.append(f"   {task.description}")
            lines.append("")

        if context.open_questions:
            lines.append("## Open Questions")
            lines.append("")
            for question in context.open_questions:
                lines.append(f"- {question}")
            lines.append("")

        return "\n".join(lines)
